# Generated by Django 4.0.5 on 2022-06-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('annee', models.DateTimeField(auto_now=True)),
                ('niveau', models.CharField(max_length=10)),
            ],
        ),
    ]
