# Generated by Django 4.0.5 on 2022-06-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etablissement', '0001_initial'),
        ('eleve', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='etablissement',
            field=models.ManyToManyField(to='etablissement.etablissement'),
        ),
    ]
