# Generated by Django 4.0.5 on 2022-06-11 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('annee', models.DateTimeField()),
                ('niveau', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Postuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakeliGestion.eleve')),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakeliGestion.offre')),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('numeroSiret', models.IntegerField()),
                ('secteur', models.CharField(max_length=255)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakeliGestion.offre')),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='etablissement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakeliGestion.etablissement'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='offre',
            field=models.ManyToManyField(through='bakeliGestion.Postuler', to='bakeliGestion.offre'),
        ),
    ]
