# Generated by Django 4.0.5 on 2022-06-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeliGestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='offre',
        ),
        migrations.AddField(
            model_name='offre',
            name='eleve',
            field=models.ManyToManyField(to='bakeliGestion.eleve'),
        ),
    ]
