# Generated by Django 4.0.5 on 2022-06-11 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bakeliGestion', '0002_remove_eleve_offre_offre_eleve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postuler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='offre',
            name='eleve',
        ),
        migrations.AddField(
            model_name='eleve',
            name='offre',
            field=models.ManyToManyField(through='bakeliGestion.Postuler', to='bakeliGestion.offre'),
        ),
        migrations.AddField(
            model_name='postuler',
            name='eleve',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakeliGestion.eleve'),
        ),
        migrations.AddField(
            model_name='postuler',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakeliGestion.offre'),
        ),
    ]
