# Generated by Django 4.0.5 on 2022-06-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakeliGestion', '0002_alter_offre_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offre',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
